name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    # Skip CI if commit message contains `[ci skip]` in the subject
    init:
        runs-on: ubuntu-latest
        outputs:
            skip: ${{ steps.ci-skip-step.outputs.ci-skip }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - id: ci-skip-step
              uses: mstachniuk/ci-skip@master

    # Check if pre-commit hooks pass
    linting:
        needs: init
        if: ${{ needs.init.outputs.skip == 'false' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pre-commit
            - name: Check pre-commit compatibility
              run: pre-commit run --all-files --show-diff-on-failure

    # Run unit tests
    test:
        needs: linting
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python-version: [3.9]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Python dependencies
              run: |
                  pip install --upgrade pip
                  pip install -e ".[dev]"
                  mkdir -p /usr/local/lib/R/4.2/custom-site-library
            - name: Set up R
              uses: r-lib/actions/setup-r@v2
            - name: Install R dependecies
              run: |
                  install.packages(c("BiocManager"))
                  BiocManager::install("BiocParallel")
                  BiocManager::install("tradeSeq")
              shell: Rscript {0}
            - name: Unit tests
              timeout-minutes: 60
              run: python -m pytest --durations=25 --cov=tradeseq -vv
